services:

  dice-roller:
    profiles:
      - all
    image: ${DICE_ROLLER_IMAGE:-joergjo/dice-roller:latest}
    build: ./DiceRoller
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    restart: unless-stopped

  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/conf/collector-config.yaml"]
    ports:
      - "4317:4317"
    volumes:
      - type: bind
        source: ./config/collector.yaml
        target: /conf/collector-config.yaml
        read_only: true
    restart: unless-stopped
