services:
  collector:
    depends_on:
      - jaeger
      - prometheus

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.22.0
    ports:
      - "16686:16686"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3
    command:
      - "--web.enable-otlp-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
