services:
  collector:
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - HONEYCOMB_DATASET=${HONEYCOMB_DATASET}
    volumes:
      - ./config/collector.honeycomb.yaml:/conf/collector-config.yaml:ro