services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/conf/collector-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - type: bind
        source: ./config/collector.yaml
        target: /conf/collector-config.yaml
        read_only: true
    restart: unless-stopped
