receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp_grpc/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp_http/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp
  debug:
    verbosity: detailed

processors:
  batch:

extensions:
  health_check:
    
service:
  telemetry:
    logs:
      level: debug
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc/jaeger]
    metrics:
       receivers: [otlp]
       processors: [batch]
       exporters: [otlp_http/prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]