global:
  scrape_interval: 15s
# Disable when using OTLP
scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['collector:8889']
      - targets: ['collector:8888']
